apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:hK12qoixlawOmoUEMlUP4VbZPfLf4fWukKbjijzAsg0=,iv:a9x9E5w2kdnR3ehpWz5PxXbTu/cqO9uecf+ao7VxVkY=,tag:nRajA/ulgbltTdLYJJuOkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1guqhes8hgyuuvuwgyk9fgjl2upumdfeuxh6eg0mhfpr2mkgquvvq8sx6dx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWHIxSXl6cSs3VFkweDJi
            RVF5SVlybjFtZVpiZDI5UTVJU0krc2M1U0dFCnY3cmpXK0FzTm1rUjhyZXFiOWpr
            QWV5NG0va3BSNUhkZ1BGNlZtUkxmU2MKLS0tIDdJQXdpTXZ3b1Ezb2NCSVJKOGxD
            QmFxMlFvRnN6eURqSmdlS2hadkIvU0kKHvOoGDA/1DXTBrQB3TyUmUftOM1e6oVl
            oFPFlnLK7PzsZoFWfYz/sQn7q/hOrizNU3wNDfrW8MZDMgtYEbqZ5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T00:50:53Z"
    mac: ENC[AES256_GCM,data:4zRgWFPKwKhS0T0h2/BHRjPx5mVniN4IV29p3WJGvPjGvJvIFlHNIVF+7rOoN0CKG7GnXRVXUCStU8OmC7xBRf1HMx3I63eONZguDzRYchiA6LXcL6xLFbVnSlLKSiH7umC1JvkoJ5qPFNhCsJv5XnfjFEwI3oFctgAkaGhOpmE=,iv:zzPOt1pp/ea67ZEYYLF0E6YwknBU7fP8S5z21L1BZkU=,tag:6oIhAf8pmj41199SCG03nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
